name: Delete Branch After Merge

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  delete-merged-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Autenticar com GH_PAT
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Deletar a branch após merge
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"

          if gh api "repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME" &>/dev/null; then
            echo "Deletando branch: $BRANCH_NAME"
            gh api -X DELETE \
              "repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME"
          else
            echo "⚠️ Branch '$BRANCH_NAME' já foi deletada ou não existe."
          fi
